services:
  - type: web
    name: sniper-solana
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    pythonVersion: 3.11.11
    envVars:
      - key: PORT
        value: 10000
