services:
  - type: worker
    name: sniper-solana
    env: python
    buildCommand: |
      python3 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      . venv/bin/activate
      python3 app.py
    pythonVersion: 3.11.11
